# Generated by Django 4.2.4 on 2023-08-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='display_name',
            field=models.CharField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app_user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='last_name',
            field=models.CharField(),
        ),
    ]
