# Generated by Django 4.2.4 on 2023-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_app_user_display_name_app_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
