# Generated by Django 4.2.4 on 2023-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_app_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='display_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
